dec_pyr:
  d_inner: 1024
  d_k: 32
  d_model: 256
  d_v: 32
  dropout_rate: 0.0
  inp_len: 256
  n_heads: 8
  n_layers: 8
  n_vocab: 50259
  step: 2
enc_pyr:
  d_inner: 1024
  d_k: 32
  d_model: 256
  d_v: 32
  dropout_rate: 0.0
  inp_len: 256
  n_heads: 8
  n_layers: 8
  pad_idx: 50257
  step: 2
  vocab_encoder:
    d_model: 256
    d_word_vec: 256
    dropout_rate: 0.0
    inp_len: 256
    n_vocab: 50259
    pad_idx: 50257
