add_token_type_ids: false
bert_agg_n_subseq_toks: 2
bert_agg_type: sep
cnv_conv_kernel_size: 3
cnv_n_layers_per_level: 1
cnv_n_levels: 1
cnv_pool_kernel_size: 2
cnv_pool_stride: 2
cnv_share_layer_weights: false
ctx_que_prompt_type: tok
d_model: 768
dec_expert_type: non
join_ctx_que_agg: false
max_inp_toks: 384
max_out_toks: 50
model_name: bert-base-uncased
moe_experts_num: 0
pyr_agg_n_layers_per_level: 0
pyr_agg_n_levels: 0
pyr_agg_step: 2
pyr_agg_type: decim
pyr_share_layer_weights: false
share_agg_enc_token_embeds: false
toks_agg_type: brt
train_agg_model: false
