dec_simple:
  d_model: 256
dec_trans: null
dec_type: smp
enc_pyr:
  d_inner: 1024
  d_k: 32
  d_model: 256
  d_v: 32
  dropout_rate: 0.0
  inp_len: 256
  n_heads: 8
  n_layers: 8
  n_similar_layers: 1
  pad_idx: 50267
  reduct_type: matmul
  step: 2
  vocab_encoder:
    d_model: 256
    d_word_vec: 256
    dropout_rate: 0.0
    inp_len: 256
    n_vocab: 50271
    pad_idx: 50267
    pos_enc_type: num
