custom_tokens:
  mask:
    ind: 50258
    name: mask
    repr: <|mask|>
    special: false
  pad:
    ind: 50257
    name: pad
    repr: <|pad|>
    special: true
model_max_length: 10000
n_tokens_init: 50257
name: gpt2
