decoders:
- d_inner: 1024
  d_k: 32
  d_model: 256
  d_v: 32
  dropout_rate: 0.0
  inp_len: 0
  n_heads: 8
  n_layers: 1
  pad_idx: -1
  with_emb_mat: false
  with_graph_mat: false
encoders:
- d_inner: 1024
  d_k: 32
  d_model: 256
  d_v: 32
  dropout_rate: 0.0
  inp_len: 100
  n_heads: 8
  n_layers: 1
  pad_idx: -1
  with_emb_mat: true
  with_graph_mat: false
vocab_encoder:
  d_model: 256
  d_word_vec: 256
  dropout_rate: 0.0
  inp_len: 100
  n_vocab: 50257
  pad_idx: -1
