"""Key-value recall dataset (structured-extraction family §2.1).

Automated, but grounded in *real* Wikipedia text: each record is a list of
``key: value`` pairs whose **keys** and **values** are real words / spans sampled
from a Wikipedia article. The decoder is prompted with one key and must emit the
paired value. The value lives *only* in the encoded record (priors cannot supply
it), so the cheapest path to low loss runs through the context embeddings — the
forcing function described in
``docs/mixed_decoder/data_extraction/autogenerated_plan.md`` §0.

The dataset emits the same ``MaskedCiteBatch`` shape the ``Cite`` task uses, so it
drops straight into ``MixedDecoder.run_on_text_citation`` with no model changes.
Differences from the ``Cite`` task:

* The encoder input is **unmasked** (``inp_masked_toks == inp_toks``): the value
  is the needle and must be visible to the encoder.
* The prompt is a *structured query* (a key) rather than two random anchor tokens.
* The target (``cites_*``) is the value paired with the queried key.

Use with ``--train-ds-type keyval`` and ``--prompt-all false`` (the target is the
value, not the whole record).
"""
from dataclasses import dataclass
from typing import Generator, List, Optional

import numpy as np
import torch
import torch.distributed as dist
from datasets import Dataset
from transformers import PreTrainedTokenizer

from mllm.data.utils import TokensSubsetV2
from mllm.train.encdec_graph_bert import MaskedCiteBatch


@dataclass(kw_only=True)
class KeyValRecallCfg:
    # Number of key:value pairs per record (the capacity knob).
    min_pairs: int = 4
    max_pairs: int = 12
    # Value length in *words* (a value is 1..value_max_words consecutive real words).
    value_min_words: int = 1
    value_max_words: int = 3
    # Minimum decoded length (chars) for a token-run to qualify as a key word.
    min_key_chars: int = 2


class KeyValRecallTokenizer:
    """Builds one ``TokensSubsetV2`` key-value-recall sample per input text."""

    def __init__(
            self, tkz_enc: PreTrainedTokenizer, max_len: int, cfg: Optional[KeyValRecallCfg] = None,
            n_special_toks: int = 1000, tkz_dec: Optional[PreTrainedTokenizer] = None,
            seed: Optional[int] = None,
    ):
        self.tkz_enc = tkz_enc
        self.tkz_dec = tkz_dec if tkz_dec is not None else tkz_enc
        self.same_vocab = self.tkz_enc is self.tkz_dec or len(self.tkz_enc) == len(self.tkz_dec)
        self.max_len = max_len
        self.cfg = cfg if cfg is not None else KeyValRecallCfg()
        self.rng = np.random.default_rng(seed)

        # Random-token pool used to top up keys/values for very short articles
        # (mirrors RandomInputTokenizerV2's anchor pool).
        self.pool = self.rng.permutation(np.arange(n_special_toks, len(self.tkz_enc)))
        self.pool_cur = 0

        # Separator token sequences (encoder vocab). Randomized per sample so the
        # model cannot learn a fixed-format position (anti-shortcut, plan §6).
        self.kv_sep_choices = [
            self.tkz_enc(s, add_special_tokens=False).input_ids for s in (':', ' :', ' =', ' -')
        ]
        self.pair_sep_choices = [
            self.tkz_enc(s, add_special_tokens=False).input_ids for s in (';', ' ;', ' .', ' |')
        ]

        # Decoder-vocab prompt template: 'Key: "<key>". Retrieve its value.'
        td = self.tkz_dec
        self.prompt_beg = td('Key: "', add_special_tokens=False).input_ids
        self.prompt_end = td('". Retrieve its value.', add_special_tokens=False).input_ids
        self.dec_end_token_id = (
            td.sep_token_id if td.sep_token_id is not None else td.eos_token_id
        )

    # --- helpers -------------------------------------------------------------
    def _next_pool_token(self) -> int:
        tid = int(self.pool[self.pool_cur])
        self.pool_cur += 1
        if self.pool_cur >= len(self.pool):
            self.rng.shuffle(self.pool)
            self.pool_cur = 0
        return tid

    def _enc_to_dec(self, enc_ids: List[int]) -> List[int]:
        if self.same_vocab:
            return list(enc_ids)
        if not enc_ids:
            return []
        text = self.tkz_enc.decode(enc_ids, skip_special_tokens=True)
        return self.tkz_dec(text, add_special_tokens=False).input_ids

    def _split_words(self, ids: List[int]) -> List[List[int]]:
        """Group WordPiece ids into whole words (a word = a non-'##' token followed
        by its '##' continuations)."""
        toks = self.tkz_enc.convert_ids_to_tokens(ids)
        words: List[List[int]] = []
        cur: List[int] = []
        for tid, tok in zip(ids, toks):
            if tok.startswith('##') and cur:
                cur.append(tid)
            else:
                if cur:
                    words.append(cur)
                cur = [tid]
        if cur:
            words.append(cur)
        return words

    def _is_key_word(self, txt: str) -> bool:
        return len(txt) >= self.cfg.min_key_chars and any(c.isalnum() for c in txt)

    # --- main ----------------------------------------------------------------
    def build(self, text: str) -> TokensSubsetV2:
        cfg = self.cfg
        ids = self.tkz_enc(text, add_special_tokens=False).input_ids
        words = self._split_words(ids)
        word_txts = [self.tkz_enc.decode(w) for w in words]

        # Distinct key-candidate words (by lowercased text).
        key_cands: List[List[int]] = []
        seen = set()
        order = self.rng.permutation(len(words))
        for wi in order:
            txt = word_txts[wi].strip()
            low = txt.lower()
            if self._is_key_word(txt) and low not in seen:
                seen.add(low)
                key_cands.append(words[wi])

        n_pairs = int(self.rng.integers(cfg.min_pairs, cfg.max_pairs + 1))
        budget = self.max_len - 2  # reserve CLS + SEP

        pairs: List[tuple] = []  # (key_ids, value_ids)
        used_len = 0
        kv_sep = self.kv_sep_choices[int(self.rng.integers(len(self.kv_sep_choices)))]
        pair_sep = self.pair_sep_choices[int(self.rng.integers(len(self.pair_sep_choices)))]

        for p in range(n_pairs):
            # Key: a distinct real word, or a random-pool token if we run out.
            if p < len(key_cands):
                key_ids = key_cands[p]
            else:
                key_ids = [self._next_pool_token()]

            # Value: 1..value_max_words consecutive real words; pool fallback.
            if words:
                c = int(self.rng.integers(cfg.value_min_words, cfg.value_max_words + 1))
                w0 = max(0, int(self.rng.integers(len(words) - c + 1)))
                value_ids: List[int] = []
                for w in words[w0:w0 + c]:
                    value_ids.extend(w)
            else:
                value_ids = [self._next_pool_token()]

            add_len = len(key_ids) + len(kv_sep) + len(value_ids) + (len(pair_sep) if pairs else 0)
            if pairs and used_len + add_len > budget:
                break
            # Always keep at least one pair, trimming the value if needed.
            if not pairs and len(key_ids) + len(kv_sep) + len(value_ids) > budget:
                keep = max(1, budget - len(key_ids) - len(kv_sep))
                value_ids = value_ids[:keep]
                add_len = len(key_ids) + len(kv_sep) + len(value_ids)
            pairs.append((key_ids, value_ids))
            used_len += add_len

        # Serialize record (encoder vocab): k1 sep v1 PAIRSEP k2 sep v2 ...
        record: List[int] = []
        for i, (k, v) in enumerate(pairs):
            if i > 0:
                record.extend(pair_sep)
            record.extend(k)
            record.extend(kv_sep)
            record.extend(v)
        record = record[:budget]

        cls_id = self.tkz_enc.cls_token_id
        sep_id = self.tkz_enc.sep_token_id
        toks_inp = [cls_id] + record + [sep_id]

        # Queried pair.
        qi = int(self.rng.integers(len(pairs)))
        key_ids_q, value_ids_q = pairs[qi]
        key_text = self.tkz_enc.decode(key_ids_q, skip_special_tokens=True)

        # Decoder-vocab pieces.
        key_dec = self.tkz_dec(key_text, add_special_tokens=False).input_ids
        prompt_toks = self.prompt_beg + key_dec + self.prompt_end
        prompt = self.tkz_dec.decode(prompt_toks, skip_special_tokens=False)

        value_dec = self._enc_to_dec(value_ids_q)
        end_suffix = [self.dec_end_token_id] if self.dec_end_token_id is not None else []
        cites_dec = value_dec + end_suffix

        record_dec = self._enc_to_dec(record)
        inp_toks_dec = record_dec + end_suffix

        return TokensSubsetV2(
            toks_src=ids,
            inp_beg_ind=0,
            inp_end_ind=len(ids),
            toks_inp=toks_inp,
            toks_inp_masked=list(toks_inp),  # no encoder masking: value is the needle
            cite_beg_ind=-1,
            cite_end_ind=-1,
            toks_cite=value_ids_q,
            toks_cite_masked=list(value_ids_q),
            toks_cite_beg=[],
            toks_cite_end=[],
            prompt=prompt,
            toks_prompt=prompt_toks,
            toks_inp_dec=inp_toks_dec,
            toks_inp_masked_dec=list(inp_toks_dec),
            toks_cite_dec=cites_dec,
            toks_cite_masked_dec=list(cites_dec),
        )

    def __call__(self, texts: List[str]) -> List[TokensSubsetV2]:
        return [self.build(t) for t in texts]


class KeyValRecallDataset:
    """Wraps a HuggingFace ``text`` dataset (e.g. Wikipedia) and yields
    ``MaskedCiteBatch`` objects with key-value-recall content."""

    def __init__(
            self, dataset: Dataset, tkz_enc: PreTrainedTokenizer, max_seq_len: int,
            n_special_toks: int = 1000, cfg: Optional[KeyValRecallCfg] = None,
            device: Optional[torch.device] = None, tkz_dec: Optional[PreTrainedTokenizer] = None,
            seed: Optional[int] = None,
    ):
        self.dataset = dataset
        self.tkz_enc = tkz_enc
        self.tkz_dec = tkz_dec if tkz_dec is not None else tkz_enc
        self.size = len(dataset)
        self.max_seq_len = max_seq_len
        self.device = device if device is not None else torch.device('cpu')
        self.enc_pad_token_id = tkz_enc.pad_token_id
        self.dec_pad_token_id = self.tkz_dec.pad_token_id
        if self.dec_pad_token_id is None:
            self.dec_pad_token_id = self.tkz_dec.eos_token_id
        self.inds = np.arange(self.size)
        self.builder = KeyValRecallTokenizer(
            tkz_enc, max_len=max_seq_len, cfg=cfg, n_special_toks=n_special_toks,
            tkz_dec=self.tkz_dec, seed=seed,
        )

    def __len__(self):
        return self.size

    def _to_tensor(self, toks_list: List[List[int]], pad_token_id: int, with_att_mask: bool):
        batch_size = len(toks_list)
        max_len = max((len(t) for t in toks_list), default=1)
        max_len = max(max_len, 1)
        out = torch.full((batch_size, max_len), pad_token_id, dtype=torch.long, device=self.device)
        att = torch.zeros((batch_size, max_len), dtype=torch.long, device=self.device) if with_att_mask else None
        for i, toks in enumerate(toks_list):
            n = len(toks)
            if n:
                out[i, :n] = torch.tensor(toks, dtype=torch.long, device=self.device)
            if att is not None:
                att[i, :n] = 1
        return out, att

    def get_batch(self, inds: List[int]) -> MaskedCiteBatch:
        texts = [self.dataset[int(i)]['text'] for i in inds]
        subsets = self.builder(texts)
        batch_size = len(inds)
        enc_pad, dec_pad = self.enc_pad_token_id, self.dec_pad_token_id

        inp_toks, inp_att_mask = self._to_tensor([s.toks_inp for s in subsets], enc_pad, True)
        inp_masked_toks, _ = self._to_tensor([s.toks_inp_masked for s in subsets], enc_pad, False)
        prompts_toks, prompts_att_mask = self._to_tensor([s.toks_prompt for s in subsets], dec_pad, True)
        cites_toks, cites_att_mask = self._to_tensor([s.toks_cite_dec for s in subsets], dec_pad, True)
        cites_masked_toks, _ = self._to_tensor([s.toks_cite_masked_dec for s in subsets], dec_pad, False)
        inp_toks_dec, inp_dec_att_mask = self._to_tensor([s.toks_inp_dec for s in subsets], dec_pad, True)
        inp_masked_toks_dec, _ = self._to_tensor([s.toks_inp_masked_dec for s in subsets], dec_pad, False)
        edge_inds = torch.stack([
            torch.arange(batch_size, device=self.device),
            torch.full((batch_size,), batch_size, device=self.device),
        ])

        return MaskedCiteBatch(
            tokens_subsets=subsets,
            inp_toks=inp_toks,
            inp_masked_toks=inp_masked_toks,
            prompts_toks=prompts_toks,
            cites_masked_toks=cites_masked_toks,
            cites_toks=cites_toks,
            inp_att_mask=inp_att_mask,
            prompts_att_mask=prompts_att_mask,
            cites_att_mask=cites_att_mask,
            inp_toks_dec=inp_toks_dec,
            inp_masked_toks_dec=inp_masked_toks_dec,
            inp_dec_att_mask=inp_dec_att_mask,
            edge_inds=edge_inds,
        )

    def shuffle(self, seed: Optional[int] = None) -> 'KeyValRecallDataset':
        if seed is not None:
            np.random.default_rng(seed).shuffle(self.inds)
        else:
            np.random.shuffle(self.inds)
        return self


def create_key_val_recall_dataloader(
        dataset: KeyValRecallDataset, batch_size: int,
) -> Generator[MaskedCiteBatch, None, None]:
    rank = dist.get_rank() if dist.is_initialized() else 0
    print(f'R{rank}. Create KeyValRecallDataset dataloader. batch_size={batch_size}.')
    start_ind = 0
    while True:
        end_ind = min(start_ind + batch_size, len(dataset))
        inds = dataset.inds[start_ind:end_ind].tolist()
        if len(inds) < batch_size:
            inds += dataset.inds[:(batch_size - len(inds))].tolist()
        batch = dataset.get_batch(inds)
        if end_ind == len(dataset):
            print(f'R{rank}. Shuffle dataset')
            dataset.shuffle()
        yield batch
        start_ind = end_ind % len(dataset)
